kind: Deployment
apiVersion: apps/v1
metadata:
  name: veldeploy


spec:
  replicas: 1
  selector:
    matchLabels:
      env: qa


  template:
    metadata:
      name: velpod
      labels:
        env: qa


    spec:
      containers:
        - name: vel-1
          image: shantanu312/micros:1.0
          ports:
            - containerPort: 8080
